# 11-03-2026
"""
Excel Population Script
------------------------

Purpose:
Generate 3 Excel sheets:
    1. matched
    2. unmatched_awbs
    3. unmatched_invoices

Data Sources:
    - awb_all_output.txt
    - invoice_all_output.txt
    - matched_results.json   (Generated by matching engine)

Design Principle:
    Matching logic is NOT re-evaluated here.
    We ONLY trust matched_results.json.

Author: <You>
Date: 2026
"""

import os
import json
from datetime import datetime
import pandas as pd

# ============================================================
# 📂 PATH CONFIGURATION
# ============================================================

BASE_DIR = r"C:\Users\SONIARN\OneDrive - Mercedes-Benz (corpdir.onmicrosoft.com)\DWT_TANGO - Documents"

AWB_PATH = os.path.join(BASE_DIR, "awb_all_output.txt")
INV_PATH = os.path.join(BASE_DIR, "invoice_all_output.txt")
MATCH_PATH = os.path.join(BASE_DIR, "matched_results.json")

OUTPUT_EXCEL = os.path.join(BASE_DIR, "reconciliation_output.xlsx")


# ============================================================
# 🔧 UTILITY FUNCTIONS
# ============================================================

def load_json_blocks(path):
    """
    Loads multiple JSON objects separated by dashed lines
    from .txt file.
    """
    with open(path, "r", encoding="utf-8") as f:
        raw = f.read()

    blocks = raw.split("--------------------------------------------------------------------------------")
    objects = []

    for block in blocks:
        block = block.strip()
        if not block:
            continue
        try:
            objects.append(json.loads(block))
        except json.JSONDecodeError:
            continue

    return objects


def load_matched_results(path):
    """
    Loads matched results from JSON file that may be wrapped in square brackets.
    Handles both array format and single object format.
    """
    with open(path, "r", encoding="utf-8") as f:
        content = f.read().strip()
    
    # Remove outer square brackets if present
    if content.startswith('[') and content.endswith(']'):
        content = content[1:-1].strip()
    
    # Split by comma and clean up each JSON object
    objects = []
    if content:
        # Split by comma but handle nested objects properly
        parts = []
        brace_count = 0
        current_part = ""
        
        for char in content:
            if char == '{':
                brace_count += 1
            elif char == '}':
                brace_count -= 1
            
            current_part += char
            
            # Split on comma only when we're at top level (brace_count == 0)
            if char == ',' and brace_count == 0:
                parts.append(current_part[:-1])  # Remove the comma
                current_part = ""
        
        # Add the last part
        if current_part.strip():
            parts.append(current_part)
        
        for part in parts:
            part = part.strip()
            if part:
                try:
                    objects.append(json.loads(part))
                except json.JSONDecodeError:
                    continue
    
    return objects


def format_invoice_date(date_str):
    """
    Converts various date formats to dd-mm-yyyy format.
    Examples:
        '09 Jan 2026' -> '09-01-2026'
        '2026-01-09' -> '09-01-2026'
        '09/01/2026' -> '09-01-2026'
        '09-01-2026' -> '09-01-2026'
        'Jan 09, 2026' -> '09-01-2026'
    """
    if not date_str:
        return ""

    date_formats = [
        "%d %b %Y",    # 09 Jan 2026
        "%Y-%m-%d",    # 2026-01-09
        "%d/%m/%Y",    # 09/01/2026
        "%d-%m-%Y",    # 09-01-2026
        "%b %d, %Y",   # Jan 09, 2026
        "%d %B %Y",    # 09 January 2026
        "%m/%d/%Y",    # 01/09/2026 (US format)
        "%m-%d-%Y",    # 01-09-2026 (US format)
    ]

    for fmt in date_formats:
        try:
            dt = datetime.strptime(date_str.strip(), fmt)
            return dt.strftime("%d-%m-%Y")
        except ValueError:
            continue
    
    # If all formats fail, return original string
    return date_str


def safe_get(d, key):
    """
    Safely fetch key from dict.
    Returns empty string if None.
    """
    value = d.get(key)
    return "" if value is None else value


# ============================================================
# 📥 LOAD ALL DATA (ONCE)
# ============================================================

print("Loading data...")

awbs_raw = load_json_blocks(AWB_PATH)
invoices_raw = load_json_blocks(INV_PATH)

matched_results = load_matched_results(MATCH_PATH)

print(f"Loaded {len(awbs_raw)} AWBs")
print(f"Loaded {len(invoices_raw)} Invoices")
print(f"Loaded {len(matched_results)} Matching Records")


# ============================================================
# 🗂 BUILD LOOKUP DICTIONARIES (SOURCE OF TRUTH)
# ============================================================

# Key = _source_file
awb_lookup = {a["_source_file"]: a["awb"] for a in awbs_raw}
invoice_lookup = {i["_source_file"]: i["invoice"] for i in invoices_raw}


# ============================================================
# 📊 PREPARE DATA CONTAINERS
# ============================================================

matched_rows = []
unmatched_awb_rows = []
unmatched_invoice_rows = []

matched_awb_files = set()
matched_invoice_files = set()


# ============================================================
# 📘 BUILD MATCHED SHEET
# ============================================================

for entry in matched_results:

    awb_file = entry["awb_file"]
    matches = entry.get("matched_invoices", [])

    # If no matches → skip here (handled later)
    if not matches:
        continue

    matched_awb_files.add(awb_file)

    awb = awb_lookup.get(awb_file, {})

    for m in matches:

        inv_file = m["invoice_file"]
        matched_invoice_files.add(inv_file)

        invoice = invoice_lookup.get(inv_file, {})

        # Create ONE ROW per AWB-Invoice pair
        row = {

            # ========================
            # AWB FIELDS
            # ========================
            "HAWB No": safe_get(awb, "hawb"),
            "FLT_NO": safe_get(awb, "second_flight_date"),
            "Date": safe_get(awb, "executed_on_date"),
            "TYPE": safe_get(awb.get("classification", {}), "category"),

            # ========================
            # INVOICE FIELDS
            # ========================
            "PKG": safe_get(invoice, "no_pieces"),
            "GW": safe_get(invoice, "gross_weight"),
            "MBS No": safe_get(invoice, "delivery_note"),
            "MBS Date": format_invoice_date(invoice.get("invoice_date")),
            "Invoice No": safe_get(invoice, "invoice_number"),
            "INVOICEVAL": safe_get(invoice, "total_price"),
            "Currency": safe_get(invoice, "currency"),
            "Ex works Price": safe_get(invoice, "ex_factory"),
            "Packing Charges": safe_get(invoice, "packing"),
            "Charges to Airport": safe_get(invoice, "loading_charges"),
            "FOB VALUE": safe_get(invoice, "value_fob"),
            "Freight Charges": safe_get(invoice, "air_or_sea_freight_charges"),

            # ========================
            # MANUAL FIELDS (EMPTY)
            # ========================
            "CHA": "",
            "CCO_NO": "",
            "COST_CNTR": "",
            "CCO_DT": "",
            "FOC": "",
            "DSR_JobNo": "",
            "DSR_ClearanceData": "",
            "Receipt Date": "",
            "remarks": "",
            "Dup_BOE_Sub_Date": "",
            "Dup_BOE_Sub_Remark": ""
        }

        matched_rows.append(row)


# ============================================================
# 📙 BUILD UNMATCHED AWBS SHEET
# ============================================================

for awb_file, awb in awb_lookup.items():

    if awb_file in matched_awb_files:
        continue

    unmatched_awb_rows.append({
        "HAWB No": safe_get(awb, "hawb"),
        "FLT_NO": safe_get(awb, "second_flight_date"),
        "Date": safe_get(awb, "executed_on_date"),
        "TYPE": safe_get(awb.get("classification", {}), "category")
    })


# ============================================================
# 📕 BUILD UNMATCHED INVOICES SHEET
# ============================================================

for inv_file, invoice in invoice_lookup.items():

    if inv_file in matched_invoice_files:
        continue

    unmatched_invoice_rows.append({
        "Invoice No": safe_get(invoice, "invoice_number"),
        "MBS Date": format_invoice_date(invoice.get("invoice_date")),
        "PKG": safe_get(invoice, "no_pieces"),
        "GW": safe_get(invoice, "gross_weight"),
        "INVOICEVAL": safe_get(invoice, "total_price"),
        "Currency": safe_get(invoice, "currency")
    })


# ============================================================
# 📤 EXPORT TO EXCEL
# ============================================================

with pd.ExcelWriter(OUTPUT_EXCEL, engine="xlsxwriter") as writer:

    pd.DataFrame(matched_rows).to_excel(writer, sheet_name="matched", index=False)
    pd.DataFrame(unmatched_awb_rows).to_excel(writer, sheet_name="unmatched_awbs", index=False)
    pd.DataFrame(unmatched_invoice_rows).to_excel(writer, sheet_name="unmatched_invoices", index=False)

print("\n✓ Excel file generated successfully!")
print(f"Location: {OUTPUT_EXCEL}")
